In [1]:
#Data Handling Library
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('Myntra_Data_Raw.csv')
df.head()

Time (Mins) Recall Rate
0            1         84%
1            5         71%
2           15         61%
3           30         56%
4           60         54%

In [3]:
df.describe()

Time (Mins)
count     13.000000
mean    1679.307692
std     3018.230508
min        1.000000
25%       30.000000
50%      240.000000
75%     1440.000000
max    10080.000000

In [19]:
def Summary(df):
    from collections import OrderedDict
    result = []
    for col in list(df.columns):
        stats = OrderedDict({'col_name':col,
                            'Count':df[col].count(),
                             'Datatype':df[col].dtype,
                             'Min':df[col].min(),
                             'Q1':df[col].quantile(0.25),
                             'Mean':df[col].mean(),
                             'Mediam':df[col].quantile(0.50),
                             'Q3':df[col].quantile(0.75),
                             'Max':df[col].max(),
                             'Variance':df[col].var(),
                             'Stdev':df[col].std(),
                             'Skewness':df[col].skew(),
                             'Kurtosis':df[col].kurt(),
                             'Range':df[col].max() - df[col].min(),
                             'IQR': df[col].quantile(0.75) - df[col].quantile(0.25)
                            })
        
        result.append(stats)
    resultdf = pd.DataFrame(data = result)
    return resultdf

In [4]:
x = df.drop('Recall Rate', axis=1)

In [5]:
x.head()

Time (Mins)
0            1
1            5
2           15
3           30
4           60

In [6]:
y = df[["Recall Rate"]]
y.head()


Recall Rate
0         84%
1         71%
2         61%
3         56%
4         54%

In [7]:
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 20)

In [9]:
log_reg = LogisticRegression()
log_reg.fit(x_train, y_train)

C:\Users\GOD\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\GOD\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [10]:
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

LogisticRegression(multi_class='ovr', n_jobs=1, solver='liblinear')

In [11]:
model = LogisticRegression(solver='liblinear', random_state=0).fit(x, y)


C:\Users\GOD\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [12]:
model.classes_

array(['16%', '20%', '26%', '36%', '38%', '45%', '47%', '54%', '56%',
       '61%', '71%', '8%', '84%'], dtype=object)

In [13]:
model.intercept_

array([-1.55121439, -1.37740945, -1.26511479, -1.1636241 , -1.06843319,
       -0.95079124, -0.80934283, -0.66924243, -0.49004498, -0.29266895,
       -0.00440787, -1.8047457 ,  0.33961875])

In [14]:
 model.coef_

array([[ 7.60202674e-05],
       [-8.01299435e-05],
       [-2.62055410e-04],
       [-5.82234376e-04],
       [-9.63476471e-04],
       [-2.16137818e-03],
       [-4.59440187e-03],
       [-9.52657520e-03],
       [-2.07600861e-02],
       [-4.36563603e-02],
       [-1.20657029e-01],
       [ 2.40390148e-04],
       [-3.86893144e-01]])

In [15]:
model.predict_proba(x)

array([[4.48327569e-002, 5.16223318e-002, 5.63990754e-002,
        6.09751151e-002, 6.54896175e-002, 7.13265198e-002,
        7.86979362e-002, 8.62547241e-002, 9.61143153e-002,
        1.06801464e-001, 1.20147621e-001, 3.62163109e-002,
        1.25122212e-001],
       [5.16170207e-002, 5.94039032e-002, 6.48642517e-002,
        7.00599991e-002, 7.51647660e-002, 8.15880421e-002,
        8.94346242e-002, 9.67879769e-002, 1.04951430e-001,
        1.10620868e-001, 1.04017011e-001, 4.17206733e-002,
        4.97694343e-002],
       [6.17876816e-002, 7.10188493e-002, 7.74379584e-002,
        8.34405737e-002, 8.92747959e-002, 9.60842304e-002,
        1.03595704e-001, 1.08499783e-001, 1.09305075e-001,
        9.86005663e-002, 4.94524503e-002, 5.00131389e-002,
        1.48919340e-003],
       [7.04777273e-002, 8.08533707e-002, 8.79756064e-002,
        9.44538447e-002, 1.00640558e-001, 1.06930571e-001,
        1.12389866e-001, 1.11754063e-001, 9.94747635e-002,
        6.74259022e-002, 1.04484320e-

In [16]:
model.predict(x)

array(['84%', '61%', '56%', '47%', '45%', '38%', '38%', '26%', '20%',
       '16%', '8%', '8%', '8%'], dtype=object)

In [17]:
 model.score(x, y)

0.15384615384615385